# Generated by Django 3.0.8 on 2020-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
