# Generated by Django 3.1.3 on 2021-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='activiteiten_info',
            field=models.CharField(default='Tombola met mooie prijzen', max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='catering_info',
            field=models.CharField(default='Indische catering aanwezig', max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisator',
            field=models.CharField(default='Vita Nova I.O.', max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='organisator_info',
            field=models.CharField(default='Vita Nova Baru Bangkit Dari Abu.', max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='volgende_activiteiten',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='soort',
            field=models.IntegerField(choices=[(0, 'Contact'), (1, 'Lid'), (2, 'Donateur'), (3, 'Erelid'), (4, 'Artiest'), (5, 'Catering'), (6, 'Art Buro'), (7, 'Bandleider'), (8, 'Technicus'), (9, 'Beheerder'), (10, 'Media')], default=0),
        ),
    ]
