# Generated by Django 3.0.8 on 2020-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='test_field',
            field=models.CharField(blank=True, default='Test', max_length=18),
        ),
    ]
