# Generated by Django 3.0.8 on 2020-08-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field=100, null=True, upload_to='../media', width_field=100),
        ),
    ]
