# Generated by Django 3.0.8 on 2020-08-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_band_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='test_field',
        ),
    ]
