# Generated by Django 3.1.3 on 2021-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210302_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='organisator_info',
            field=models.CharField(default='Vita Nova Baru Bangkit Dari Abu.', max_length=80),
        ),
    ]
