# Generated by Django 3.0.8 on 2020-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200912_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='catering_prijs',
        ),
        migrations.AddField(
            model_name='cateraar',
            name='catering_prijs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='fanclub',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
