# Generated by Django 3.1.3 on 2021-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210303_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='volgende_activiteiten',
        ),
        migrations.AddField(
            model_name='evenement',
            name='volgende_datum_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='volgende_datum_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
