# Generated by Django 3.1.3 on 2021-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210305_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='uitverkocht',
            field=models.BooleanField(default=False),
        ),
    ]
