# Generated by Django 3.1.3 on 2021-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_evenement_uitverkocht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
