# Generated by Django 3.1.2 on 2020-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_evenement_opbrengst'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='voornaam',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
