# Generated by Django 3.1.2 on 2020-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_voornaam'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
        migrations.AddField(
            model_name='cateraar',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
        migrations.AddField(
            model_name='evenement',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
        migrations.AddField(
            model_name='fanclub',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
        migrations.AddField(
            model_name='zaal',
            name='slug',
            field=models.SlugField(default='slug', max_length=120),
        ),
    ]
