# Generated by Django 3.1.3 on 2021-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210310_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='band',
            name='band_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
