# Generated by Django 3.1.3 on 2021-03-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210311_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
