# Generated by Django 3.1.3 on 2021-04-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20210422_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='soort',
            field=models.IntegerField(choices=[(0, 'Contact'), (1, 'Lid'), (2, 'Donateur'), (3, 'Erelid'), (4, 'Artiest'), (5, 'Catering'), (6, 'Art Buro'), (7, 'Bandleider'), (8, 'Technicus'), (9, 'Beheerder'), (10, 'Media'), (11, 'Dj'), (12, 'Vereniging'), (13, 'Stichting'), (14, 'Firma')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='soort_lid',
            field=models.IntegerField(choices=[(0, 'Blanco'), (1, 'Brons'), (2, 'Zilver'), (3, 'Goud'), (4, 'Acara Kampalan'), (5, 'Dansen'), (6, 'Line Dance'), (7, 'Oosterkerk'), (8, 'Rock Pop')], default=0),
        ),
    ]
