# Generated by Django 3.1.3 on 2021-05-10 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20210430_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verkoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('betaald', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
                ('slug', models.SlugField(default='slug', max_length=120)),
                ('datum_inserted', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.evenement')),
            ],
            options={
                'verbose_name_plural': 'verkoop',
                'ordering': ['evenement'],
            },
        ),
    ]
