# Generated by Django 3.1.3 on 2021-05-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_verkoop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verkoop',
            new_name='Ticket',
        ),
    ]
