# Generated by Django 3.1.3 on 2021-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20210510_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='voorverkoop',
            field=models.BooleanField(default=False),
        ),
    ]
