# Generated by Django 3.1.3 on 2021-05-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_ticket_voorverkoop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='aantal',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=3),
        ),
    ]
