# Generated by Django 3.1.3 on 2021-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20210510_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='slug',
        ),
    ]
