# Generated by Django 3.1.3 on 2022-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20210907_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='volgende_datum_1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='volgende_datum_2',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
