version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8010:8010"
    volumes:
      - ./contacts:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
