# Generated by Django 3.1.3 on 2021-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20210811_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='activiteiten_info',
            field=models.CharField(default='Tombola met mooie prijzen', max_length=50),
        ),
    ]
